# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s31', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
