# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s31', '0007_delete_shedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('position', models.CharField(max_length=255, verbose_name='\u0414\u043e\u043b\u0436\u043d\u043e\u0441\u0442\u044c')),
                ('number', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
            ],
        ),
    ]
